### ISSUE TITLE
this site is not working

### ISSUE THREAD

**Issue by gayatrik26** [deepaksuthar40128/Codechef-API#5]

**Comment by deepaksuthar40128** [comment]
@gayatrik26  can you please share you browser details

**Comment by gayatrik26** [comment]
Username: gayatri_03
but the issue is with the vercel link, it says "This site can’t be reached"

**Comment by deepaksuthar40128** [comment]
hey, the issue is because it was trying to get your contest rating.
Check it now.
API may behave sometime slow due to codechef ratelimiters.

**Comment by gayatrik26** [comment]
still same
"https://codechef-api.vercel.app/handle/gayatri_03", this URL is saying cannot reach site, could you pls tell me where m I going wrong

**Comment by deepaksuthar40128** [comment]
Try to visit in incognito mode may be cache issue

![image](https://github.com/user-attachments/assets/8a523acb-e663-4d28-9056-800167e2a490)

**Comment by gayatrik26** [comment]
![image](https://github.com/user-attachments/assets/9bc00ab7-e711-43d2-9a00-2597e8bd329e)
i really don't understand what is wrong😭

**Comment by deepaksuthar40128** [comment]
Seems like 🐞y network
Ain’t nothing to do here
